import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'

export default withMermaid(
  defineConfig({
    title: 'Senior Full-Stack Interview Handbook',
    description:
      'Interview-dense handbook for mid → senior full-stack roles: JS, Browser, TS, React, Next.js, Node, Backend, System Design, Coding.',
    cleanUrls: true,
    lastUpdated: true,
    themeConfig: {
      logo: undefined,
      nav: [
        { text: 'Home', link: '/' },
        {
          text: 'Frontend',
          items: [
            { text: 'JavaScript', link: '/javascript/01-fundamentals' },
            { text: 'Browser', link: '/browser/01-architecture' },
            { text: 'TypeScript', link: '/typescript/01-type-system' },
            { text: 'React', link: '/react/01-fiber' },
            { text: 'Next.js', link: '/nextjs/01-app-router' },
            { text: 'FE System Design', link: '/frontend-system-design/index' },
            { text: 'Machine Coding', link: '/machine-coding/index' },
          ],
        },
        {
          text: 'Backend',
          items: [
            { text: 'Node + Express', link: '/node/01-libuv' },
            { text: 'Backend Engineering', link: '/backend/01-api-design' },
            { text: 'Backend System Design', link: '/backend-system-design/index' },
          ],
        },
        { text: 'Coding', link: '/coding/index' },
        { text: 'Senior Q&A', link: '/senior-qa/index' },
      ],
      sidebar: {
        '/javascript/': [
          {
            text: 'JavaScript Deep Dive',
            collapsed: false,
            items: [
              { text: '1. Fundamentals Revisited', link: '/javascript/01-fundamentals' },
              { text: '2. Execution Context', link: '/javascript/02-execution-context' },
              { text: '3. Scope & Lexical Environment', link: '/javascript/03-scope' },
              { text: '4. Hoisting', link: '/javascript/04-hoisting' },
              { text: '5. Closures', link: '/javascript/05-closures' },
              { text: '6. this Keyword', link: '/javascript/06-this' },
              { text: '7. Prototype Chain', link: '/javascript/07-prototype' },
              { text: '8. Classes', link: '/javascript/08-classes' },
              { text: '9. Functions', link: '/javascript/09-functions' },
              { text: '10. Event Loop', link: '/javascript/10-event-loop' },
              { text: '11. Asynchronous JS', link: '/javascript/11-async' },
              { text: '12. Memory Management', link: '/javascript/12-memory' },
              { text: '13. Modules', link: '/javascript/13-modules' },
              { text: '14. Objects', link: '/javascript/14-objects' },
              { text: '15. Arrays', link: '/javascript/15-arrays' },
              { text: '16. Strings', link: '/javascript/16-strings' },
              { text: '17. Numbers', link: '/javascript/17-numbers' },
              { text: '18. Error Handling', link: '/javascript/18-errors' },
              { text: '19. Browser APIs', link: '/javascript/19-browser-apis' },
              { text: '20. Browser Rendering', link: '/javascript/20-rendering' },
              { text: '21. Security', link: '/javascript/21-security' },
              { text: '22. Performance', link: '/javascript/22-performance' },
              { text: '23. Machine Coding Utils', link: '/javascript/23-machine-coding' },
              { text: '24. 150 Senior JS Q&A', link: '/javascript/24-senior-js-qa' },
            ],
          },
        ],
        '/browser/': [
          {
            text: 'Browser Internals',
            items: [
              { text: 'Architecture', link: '/browser/01-architecture' },
              { text: 'Rendering Pipeline', link: '/browser/02-rendering-pipeline' },
              { text: 'Event Loop', link: '/browser/03-event-loop' },
              { text: 'CSS Internals', link: '/browser/04-css-internals' },
              { text: 'Networking', link: '/browser/05-networking' },
              { text: 'Security', link: '/browser/06-security' },
              { text: 'Memory & GC', link: '/browser/07-memory-gc' },
              { text: 'Storage', link: '/browser/08-storage' },
              { text: 'Rendering Optimization', link: '/browser/09-optimization' },
              { text: 'Interview Q&A', link: '/browser/10-interview-qa' },
            ],
          },
        ],
        '/typescript/': [
          {
            text: 'TypeScript Deep Dive',
            items: [
              { text: 'Type System Internals', link: '/typescript/01-type-system' },
              { text: 'Generics', link: '/typescript/02-generics' },
              { text: 'Conditional Types', link: '/typescript/03-conditional-types' },
              { text: 'Infer', link: '/typescript/04-infer' },
              { text: 'Utility Types', link: '/typescript/05-utility-types' },
              { text: 'Declaration Merging', link: '/typescript/06-declaration-merging' },
              { text: 'Module Resolution', link: '/typescript/07-module-resolution' },
              { text: 'Structural Typing', link: '/typescript/08-structural-typing' },
              { text: 'Variance', link: '/typescript/09-variance' },
              { text: 'Common Pitfalls', link: '/typescript/10-pitfalls' },
              { text: 'Advanced Interview Q&A', link: '/typescript/11-interview-qa' },
            ],
          },
        ],
        '/react/': [
          {
            text: 'React Internals',
            items: [
              { text: 'Fiber Architecture', link: '/react/01-fiber' },
              { text: 'Reconciliation', link: '/react/02-reconciliation' },
              { text: 'Hooks Implementation', link: '/react/03-hooks' },
              { text: 'Concurrent Rendering', link: '/react/04-concurrent' },
              { text: 'Suspense', link: '/react/05-suspense' },
              { text: 'React Query Internals', link: '/react/06-react-query' },
              { text: 'Context vs Redux', link: '/react/07-context-redux' },
              { text: 'Rendering Optimization', link: '/react/08-optimization' },
              { text: 'Memoization', link: '/react/09-memoization' },
              { text: 'Server Components', link: '/react/10-rsc' },
              { text: 'React Compiler', link: '/react/11-compiler' },
              { text: 'Interview Q&A', link: '/react/12-interview-qa' },
            ],
          },
        ],
        '/nextjs/': [
          {
            text: 'Next.js',
            items: [
              { text: 'App Router', link: '/nextjs/01-app-router' },
              { text: 'RSC', link: '/nextjs/02-rsc' },
              { text: 'SSR', link: '/nextjs/03-ssr' },
              { text: 'ISR', link: '/nextjs/04-isr' },
              { text: 'SSG', link: '/nextjs/05-ssg' },
              { text: 'Hydration', link: '/nextjs/06-hydration' },
              { text: 'Streaming', link: '/nextjs/07-streaming' },
              { text: 'Route Handlers', link: '/nextjs/08-route-handlers' },
              { text: 'Middleware', link: '/nextjs/09-middleware' },
              { text: 'Caching', link: '/nextjs/10-caching' },
              { text: 'Server Actions', link: '/nextjs/11-server-actions' },
              { text: 'Authentication', link: '/nextjs/12-authentication' },
              { text: 'Deployment', link: '/nextjs/13-deployment' },
              { text: 'Interview Q&A', link: '/nextjs/14-interview-qa' },
            ],
          },
        ],
        '/node/': [
          {
            text: 'Node.js + Express',
            items: [
              { text: 'libuv', link: '/node/01-libuv' },
              { text: 'Event Loop Phases', link: '/node/02-event-loop' },
              { text: 'Streams', link: '/node/03-streams' },
              { text: 'Buffers', link: '/node/04-buffers' },
              { text: 'Cluster', link: '/node/05-cluster' },
              { text: 'Worker Threads', link: '/node/06-worker-threads' },
              { text: 'V8', link: '/node/07-v8' },
              { text: 'JWT & Auth', link: '/node/08-jwt-auth' },
              { text: 'Middleware Internals', link: '/node/09-middleware' },
              { text: 'Scaling', link: '/node/10-scaling' },
              { text: 'Performance', link: '/node/11-performance' },
              { text: 'Security', link: '/node/12-security' },
              { text: 'Production Architecture', link: '/node/13-production' },
              { text: 'Interview Q&A', link: '/node/14-interview-qa' },
            ],
          },
        ],
        '/backend/': [
          {
            text: 'Backend Engineering',
            items: [
              { text: 'API Design', link: '/backend/01-api-design' },
              { text: 'SQL & Indexes', link: '/backend/02-sql' },
              { text: 'NoSQL Trade-offs', link: '/backend/03-nosql' },
              { text: 'ORM vs Query Builder', link: '/backend/04-orm' },
              { text: 'Redis Caching', link: '/backend/05-redis' },
              { text: 'Queues & Messaging', link: '/backend/06-queues' },
              { text: 'Auth at Scale', link: '/backend/07-auth' },
              { text: 'Rate Limit & Idempotency', link: '/backend/08-rate-limit' },
              { text: 'Observability', link: '/backend/09-observability' },
              { text: 'Deployment & Ops', link: '/backend/10-ops' },
              { text: 'Interview Q&A', link: '/backend/11-interview-qa' },
            ],
          },
        ],
        '/backend-system-design/': [
          {
            text: 'Backend System Design',
            items: [
              { text: 'Overview', link: '/backend-system-design/index' },
              { text: 'URL Shortener', link: '/backend-system-design/01-url-shortener' },
              { text: 'News Feed', link: '/backend-system-design/02-news-feed' },
              { text: 'Chat / Messaging', link: '/backend-system-design/03-chat' },
              { text: 'Rate Limiter', link: '/backend-system-design/04-rate-limiter' },
              { text: 'Notification System', link: '/backend-system-design/05-notifications' },
              { text: 'File Upload / CDN', link: '/backend-system-design/06-file-cdn' },
              { text: 'Search Autocomplete', link: '/backend-system-design/07-autocomplete' },
              { text: 'Job Queue', link: '/backend-system-design/08-job-queue' },
              { text: 'Multi-tenant SaaS API', link: '/backend-system-design/09-saas-api' },
              { text: 'Auth Service', link: '/backend-system-design/10-auth-service' },
              { text: 'Cache Layer', link: '/backend-system-design/11-cache-layer' },
            ],
          },
        ],
        '/frontend-system-design/': [
          {
            text: 'Frontend System Design',
            items: [
              { text: 'Overview', link: '/frontend-system-design/index' },
              { text: 'News Feed UI', link: '/frontend-system-design/01-feed' },
              { text: 'Autocomplete', link: '/frontend-system-design/02-autocomplete' },
              { text: 'Chat UI', link: '/frontend-system-design/03-chat' },
              { text: 'Design System', link: '/frontend-system-design/04-design-system' },
              { text: 'Image Gallery', link: '/frontend-system-design/05-image-gallery' },
              { text: 'Dashboard / Analytics', link: '/frontend-system-design/06-dashboard' },
              { text: 'Observability (FE)', link: '/frontend-system-design/07-observability' },
            ],
          },
        ],
        '/coding/': [
          {
            text: 'Coding Interview',
            items: [
              { text: 'Overview & Patterns', link: '/coding/index' },
              { text: 'Debounce / Throttle', link: '/coding/01-debounce-throttle' },
              { text: 'Promise from Scratch', link: '/coding/02-promise' },
              { text: 'EventEmitter', link: '/coding/03-event-emitter' },
              { text: 'Deep Clone', link: '/coding/04-deep-clone' },
              { text: 'LRU Cache', link: '/coding/05-lru' },
              { text: 'Flatten / Trie', link: '/coding/06-flatten-trie' },
              { text: 'Binary Search', link: '/coding/07-binary-search' },
              { text: 'Sliding Window', link: '/coding/08-sliding-window' },
              { text: 'Graphs', link: '/coding/09-graphs' },
              { text: 'Dynamic Programming', link: '/coding/10-dp' },
              { text: 'Problems 1–25', link: '/coding/11-problems-01-25' },
              { text: 'Problems 26–50', link: '/coding/12-problems-26-50' },
              { text: 'Problems 51–75', link: '/coding/13-problems-51-75' },
              { text: 'Problems 76–100', link: '/coding/14-problems-76-100' },
            ],
          },
        ],
        '/senior-qa/': [
          {
            text: 'Senior Interview Q&A',
            items: [
              { text: 'Overview', link: '/senior-qa/index' },
              { text: 'Frontend (1–40)', link: '/senior-qa/01-frontend' },
              { text: 'Backend (41–80)', link: '/senior-qa/02-backend' },
              { text: 'Full-Stack (81–120)', link: '/senior-qa/03-fullstack' },
            ],
          },
        ],
        '/machine-coding/': [
          {
            text: 'Frontend Machine Coding',
            items: [
              { text: 'Overview', link: '/machine-coding/index' },
              { text: 'Build React Query', link: '/machine-coding/01-react-query' },
              { text: 'Build Redux', link: '/machine-coding/02-redux' },
              { text: 'Infinite Scroll', link: '/machine-coding/03-infinite-scroll' },
              { text: 'Virtual List', link: '/machine-coding/04-virtual-list' },
              { text: 'Drag & Drop', link: '/machine-coding/05-drag-drop' },
              { text: 'File Upload', link: '/machine-coding/06-file-upload' },
              { text: 'Chat UI', link: '/machine-coding/07-chat-ui' },
              { text: 'Optimized Table', link: '/machine-coding/08-optimized-table' },
            ],
          },
        ],
      },
      search: { provider: 'local' },
      socialLinks: [],
      outline: { level: [2, 3] },
      editLink: undefined,
      footer: {
        message: 'Senior Full-Stack Interview Handbook',
        copyright: 'Interview-dense revision material',
      },
    },
    markdown: {
      lineNumbers: true,
    },
    mermaid: {},
  })
)
